#!/bin/bash

set -eu

VERBOSE=true
BASE_COLLECTION_PATH="must-gather"
LOG_PATH="${BASE_COLLECTION_PATH}/pmd_logs"

# print can be enabled or disabled on demand
print () {
  [[ "${VERBOSE}" ]] && echo "$@" >&2
}

get_collection_image() {
    local pod_name
    pod_name="${1:-}"
    kubectl get pods "${pod_name}" -o jsonpath='{.spec.containers[0].image}'
}

start_data_collection() {
    local node
    node="$1"
    local pod_name
    pod_name="$2"
    local image
    image="$3"
    local process
    process="$4"

    cat << EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: ${pod_name}
  labels:
    name: gather-pmd
spec:
  containers:
  - command:
    - collect
    - ${process}
    env:
    - name: TMOUT
      value: "900"
    image: ${image}
    imagePullPolicy: Always
    name: container-00
    resources: {}
    securityContext:
      privileged: true
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /host
      name: host
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostIPC: true
  hostNetwork: true
  hostPID: true
  nodeName: ${node}
  preemptionPolicy: PreemptLowerPriority
  priority: 1000000000
  priorityClassName: openshift-user-critical
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /
      type: Directory
    name: host
EOF
}

NODE_NAME="${NODE_NAME-""}"
if [ -z "${NODE_NAME}" ]; then
    echo "Must provide a node name to run collection on"
    exit 1
fi
POD_NAME="${POD_NAME-""}"
if [ -z "${POD_NAME}" ]; then
    echo "Must provide the name of the must-gather pod"
    exit 1
fi
process="${1:-}"
if [ "${process}" == "" ]; then
    echo "Please provided a process ID or process name."
    exit 1
fi

mkdir -p "${LOG_PATH}"
cd "${LOG_PATH}"
image=$(get_collection_image "${POD_NAME}")
start_data_collection "${NODE_NAME}" collect-pmd-info "${image}" "${process}"
