---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: collect-pmd-info
  labels:
    app: collect-pmd-info
spec:
  selector:
    matchLabels:
      app: collect-pmd-info
  template:
    metadata:
      labels:
        app: collect-pmd-info
    spec:
      initContainers:
      - command:
        - /bin/bash
        - /scripts/collect.sh
        image: collect-image
        imagePullPolicy: Always
        name: data-collector
        resources: {}
        securityContext:
          privileged: true
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host
          name: host
        - mountPath: /data-store
          name: data-store
        - name: scripts
          mountPath: /scripts
      containers:
      - command:
        - sleep
        - infinity
        image: collect-image
        imagePullPolicy: Always
        name: sleep-infinity
        volumeMounts:
        - mountPath: /data-store
          name: data-store
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      hostIPC: true
      hostNetwork: true
      hostPID: true
      nodeName: replace-me
      preemptionPolicy: PreemptLowerPriority
      priority: 1000000000
      priorityClassName: openshift-user-critical
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      tolerations:
      - operator: "Exists"
      volumes:
      - hostPath:
          path: /
          type: Directory
        name: host
      - emptyDir:
          sizeLimit: 10Gi
        name: data-store
      - name: scripts
        configMap:
          name: scripts
